---
# Template configuration files for laptop

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ laptop_templates_copy }}"
  when: laptop_copy_templates
